#!/usr/bin/env ruby
# frozen_string_literal: true

require 'graal_ffi'
require 'optparse'

options = { o: "#{Dir.pwd}/libgraal" }
OptionParser
  .new
  .tap { |opt| opt.on('-o [VAL]', String) }
  .parse!(ARGV, into: options)

GraalFFI::Builder.new(java_paths: ARGV, output_path: options[:o]).execute
